services:
  php-fpm:
    build:
      context: ./docker/php
    networks:
      - wow_simple_registration
    volumes:
      - ./:/app

  apache:
    image: httpd:2.4
    depends_on:
      - php-fpm
    networks:
      - wow_simple_registration
    volumes:
      - ./docker/apache/default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./:/app
    ports:
      - ${HTTP_PORT:80}:80
    environment:
      - APACHE_DOCUMENT_ROOT=/app

networks:
  wow_simple_registration: